# -*- coding: utf-8 -*-
publishFailed = u'发布失败!                           '
publishSucessed = u'发布成功!                         ' 
loginFailed =  u'登录失败!                            ' 
clickedFailed = u'打开失败!                           '  
prompt = u'提示信息                                                                   '
warning = u'警告信息                                                                '
failedCause = u'用户名或密码错误！'
remarkContent =  u'请添加备注信息!'
fileRename = u'当前文件名已经存在，请更改!'
fileNameIsNull = u"文件名为空，请输入文件名!"
imgContent = u'请添加缩略图!'
projectContent =  u"暂无项目请先创建!"
selectProject = u"请先选择一个项目!"
taskContent = u"没有可选的任务,请先去创建!"
selectTask = u"请选择一个任务!"
selectWorkFile = u"请选择工作文件!"
typeContent = u"请先选择类型!"
isNoTask = u'没有Task相关内容!'
isNoShot = u'没有Shot相关内容!'
isNoAsset = u'没有Asset相关内容!'
isNoProject = u'没有Project相关内容!'
isNoWorkFile = u"没有Work File相关内容!"