# -*- coding: utf-8 -*-
from PySide import QtCore, QtGui

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1080, 843)
        Widget.setMaximumSize(1080, 843)
        Widget.setMinimumSize(1080, 843)
        self.widget = QtGui.QWidget(Widget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1061, 761))
        self.widget.setObjectName("widget")
        self.tabWidget = QtGui.QTabWidget(self.widget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 311, 701))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.searchSA = QtGui.QLineEdit(self.widget)
        self.searchSA.setGeometry(QtCore.QRect(20, 20, 311, 20))
        self.searchSA.setObjectName("searchSA")
        self.scrollArea = QtGui.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(350, 70, 691, 681))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 689, 679))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.searchPublish = QtGui.QLineEdit(self.widget)
        self.searchPublish.setGeometry(QtCore.QRect(350, 20, 291, 20))
        self.searchPublish.setObjectName("searchPublish")
        
        self.detailBtn = QtGui.QToolButton(self.widget)
        self.detailBtn.setMinimumSize(QtCore.QSize(0, 20))
        self.detailBtn.setGeometry(QtCore.QRect(980, 40, 31, 23))
        self.detailBtn.setObjectName("detailBtn")
        self.listBtn = QtGui.QToolButton(self.widget)
        self.listBtn.setGeometry(QtCore.QRect(1010, 40, 31, 23))
        self.listBtn.setMinimumSize(QtCore.QSize(0, 20))
        self.listBtn.setObjectName("listBtn")
        
        self.selBtn = QtGui.QPushButton(Widget)
        self.selBtn.setGeometry(QtCore.QRect(820, 800, 111, 23))
        self.selBtn.setObjectName("selBtn")
        self.cancelBtn = QtGui.QPushButton(Widget)
        self.cancelBtn.setGeometry(QtCore.QRect(940, 800, 111, 23))
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(Widget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QtGui.QApplication.translate("Widget", "场景加载", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Widget", "Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Widget", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Widget", "My Task", None, QtGui.QApplication.UnicodeUTF8))
        self.detailBtn.setText(QtGui.QApplication.translate("Widget", "detail", None, QtGui.QApplication.UnicodeUTF8))
        self.listBtn.setText(QtGui.QApplication.translate("Widget", "list", None, QtGui.QApplication.UnicodeUTF8))
        self.selBtn.setText(QtGui.QApplication.translate("Widget", "选择", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelBtn.setText(QtGui.QApplication.translate("Widget", "取消", None, QtGui.QApplication.UnicodeUTF8))