# -*- coding: utf-8 -*-
from PySide import QtCore, QtGui

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(639, 586)
        Widget.setMaximumSize(639, 586)
        Widget.setMinimumSize(639, 586)
        self.imageBox = QtGui.QGroupBox(Widget)
        self.imageBox.setGeometry(QtCore.QRect(20, 150, 601, 201))
        self.imageBox.setObjectName("imageBox")
        self.contentBox = QtGui.QGroupBox(Widget)
        self.contentBox.setGeometry(QtCore.QRect(20, 360, 601, 141))
        self.contentBox.setObjectName("contentBox")
        self.contentTxt = QtGui.QTextEdit(self.contentBox)
        self.contentTxt.setGeometry(QtCore.QRect(10, 20, 581, 111))
        self.contentTxt.setObjectName("contentTxt")
        self.publishBtn = QtGui.QPushButton(Widget)
        self.publishBtn.setGeometry(QtCore.QRect(430, 530, 75, 23))
        self.publishBtn.setObjectName("publishBtn")
        self.cancelBtn = QtGui.QPushButton(Widget)
        self.cancelBtn.setGeometry(QtCore.QRect(530, 530, 75, 23))
        self.cancelBtn.setObjectName("cancelBtn")
        self.formLayoutWidget = QtGui.QWidget(Widget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 601, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.projectLabel = QtGui.QLabel(self.formLayoutWidget)
        self.projectLabel.setObjectName("projectLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.projectLabel)
        self.projectComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.projectComboBox.setObjectName("projectComboBox")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.projectComboBox)
        self.typeLabel = QtGui.QLabel(self.formLayoutWidget)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.typeLabel)
        self.typeComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.typeComboBox.setObjectName("typeComboBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.typeComboBox)
        self.taskLable = QtGui.QLabel(self.formLayoutWidget)
        self.taskLable.setObjectName("taskLable")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.taskLable)
        self.taskComboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.taskComboBox.setObjectName("taskComboBox")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.taskComboBox)
        self.fileName = QtGui.QLabel(self.formLayoutWidget)
        self.fileName.setObjectName("fileName")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.fileName)
        self.FileTxt = QtGui.QLineEdit(self.formLayoutWidget)
        self.FileTxt.setObjectName("FileTxt")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.FileTxt)
        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QtGui.QApplication.translate("Widget", "发布", None, QtGui.QApplication.UnicodeUTF8))
        self.imageBox.setTitle(QtGui.QApplication.translate("Widget", "缩略图", None, QtGui.QApplication.UnicodeUTF8))
        self.contentBox.setTitle(QtGui.QApplication.translate("Widget", "备注", None, QtGui.QApplication.UnicodeUTF8))
        self.publishBtn.setText(QtGui.QApplication.translate("Widget", "发布", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelBtn.setText(QtGui.QApplication.translate("Widget", "取消", None, QtGui.QApplication.UnicodeUTF8))
        self.projectLabel.setText(QtGui.QApplication.translate("Widget", "所属项目名", None, QtGui.QApplication.UnicodeUTF8))
        self.typeLabel.setText(QtGui.QApplication.translate("Widget", "所属类型", None, QtGui.QApplication.UnicodeUTF8))
        self.taskLable.setText(QtGui.QApplication.translate("Widget", "任务名", None, QtGui.QApplication.UnicodeUTF8))
        self.fileName.setText(QtGui.QApplication.translate("Widget", "文件名", None, QtGui.QApplication.UnicodeUTF8))


