# -*- coding: utf-8 -*-
from PySide import QtCore, QtGui

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(747, 915)
        Widget.setMaximumSize(747, 915)
        Widget.setMinimumSize(747, 915)
        self.SAGBox = QtGui.QGroupBox(Widget)
        self.SAGBox.setGeometry(QtCore.QRect(20, 20, 341, 811))
        self.SAGBox.setObjectName("SAGBox")
        self.scrollAreaForSA = QtGui.QScrollArea(self.SAGBox)
        self.scrollAreaForSA.setGeometry(QtCore.QRect(10, 60, 321, 740))
        self.scrollAreaForSA.setWidgetResizable(True)
        self.scrollAreaForSA.setObjectName("scrollAreaForSA")
        self.scrollAreaContentForSA = QtGui.QWidget()
        self.scrollAreaContentForSA.setGeometry(QtCore.QRect(0, 0, 319, 729))
        self.scrollAreaContentForSA.setObjectName("scrollAreaContentForSA")
        self.scrollAreaForSA.setWidget(self.scrollAreaContentForSA)
        self.searchSA = QtGui.QLineEdit(self.SAGBox)
        self.searchSA.setGeometry(QtCore.QRect(10, 30, 321, 21))
        self.searchSA.setObjectName("searchSA")
        self.taskGBox = QtGui.QGroupBox(Widget)
        self.taskGBox.setGeometry(QtCore.QRect(390, 20, 331, 811))
        self.taskGBox.setObjectName("taskGBox")
        self.scrollAreaForTask = QtGui.QScrollArea(self.taskGBox)
        self.scrollAreaForTask.setGeometry(QtCore.QRect(10, 60, 311, 740))
        self.scrollAreaForTask.setWidgetResizable(True)
        self.scrollAreaForTask.setObjectName("scrollAreaForTask")
        self.scrollAreaContentForTask = QtGui.QWidget()
        self.scrollAreaContentForTask.setGeometry(QtCore.QRect(0, 0, 309, 729))
        self.scrollAreaContentForTask.setObjectName("scrollAreaContentForTask")
        self.scrollAreaForTask.setWidget(self.scrollAreaContentForTask)
        self.searchTask = QtGui.QLineEdit(self.taskGBox)
        self.searchTask.setGeometry(QtCore.QRect(10, 30, 311, 20))
        self.searchTask.setObjectName("searchTask")
        self.backBtn = QtGui.QPushButton(Widget)
        self.backBtn.setGeometry(QtCore.QRect(440, 860, 75, 23))
        self.backBtn.setObjectName("backBtn")
        self.selBtn = QtGui.QPushButton(Widget)
        self.selBtn.setGeometry(QtCore.QRect(540, 860, 75, 23))
        self.selBtn.setObjectName("selBtn")
        self.cancelBtn = QtGui.QPushButton(Widget)
        self.cancelBtn.setGeometry(QtCore.QRect(640,860, 75, 23))
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QtGui.QApplication.translate("Widget", "选择任务", None, QtGui.QApplication.UnicodeUTF8))
        self.SAGBox.setTitle(QtGui.QApplication.translate("Widget", "Shot&&Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.taskGBox.setTitle(QtGui.QApplication.translate("Widget", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.backBtn.setText(QtGui.QApplication.translate("Widget", "返回项目菜单", None, QtGui.QApplication.UnicodeUTF8))
        self.selBtn.setText(QtGui.QApplication.translate("Widget", "选择", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelBtn.setText(QtGui.QApplication.translate("Widget", "取消", None, QtGui.QApplication.UnicodeUTF8))
